# Generated by Django 5.2 on 2025-05-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["title"],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
