# Generated by Django 5.2 on 2025-04-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию товара', max_length=100, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=100, verbose_name='Наименование продукта')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='catalog/images', verbose_name='Изображение')),
                ('price', models.FloatField(help_text='Введите цену за покупку продукта', verbose_name='Цена за покупку')),
                ('created_at', models.DateField(help_text='Укажите дату создания', verbose_name='Дата создания')),
                ('upload_at', models.DateField(help_text='Укажите дату последнего изменения', verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
