# Generated by Django 5.2 on 2025-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя", max_length=50, verbose_name="Имя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=16,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Введите дополнительную информацию",
                        null=True,
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ["name"],
            },
        ),
    ]
