# Generated by Django 5.2 on 2025-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=30,
                verbose_name="Телефон",
            ),
        ),
    ]
