# Generated by Django 5.2 on 2025-05-28 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_created_at_alter_product_upload_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="catalog/media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "png"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
