# Generated by Django 5.2 on 2025-06-07 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="catalog/media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "png"],
                        message="Допустимы только файлы в формате JPEG или PNG",
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
